version: '3.8'

services:
  backend:
    image: node:14-alpine
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - APP_PORT=5008
      - APP_HOST=localhost
      - DB_CONNECTION=mysql
      - DB_PORT=3307
      - DB_USERNAME=root
      - DB_PASSWORD=mysql-password
      - DATABASE_NAME=backendtask
      - APP_SYNCHRONIZE=true
      - APP_LOGGING=false
    command: sh -c 'npm install && npm run start:dev'
    ports:
      - '5008:5008'
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=mysql-password
      - MYSQL_DATABASE=backendtask
      - MYSQL_USER=root
      - MYSQL_PASSWORD=mysql-password
    ports:
      - '3307:3306'
